import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Suspense } from "react";
import Loading from "./loading";

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Suspense fallback={<Loading />}>{children}</Suspense>
			</body>
		</html>
	);
=======
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
>>>>>>> d5dd0343244720e70ebb3cd6af91a8225b971918
}
